### ISSUE TITLE
PA Review: {User Auth}

### ISSUE THREAD

**Issue by mkochalko** [mkochalko/full_stack_project#2]
Completed frontend/backend user auth with styling. Demo login works, and the proper errors show in the correct place.

**Comment by samwalker191** [comment]
Nice! Please see below for my recommendations.

1. The errors don't clear when I go from login form to sign up form.
2. Demo User button doesn't work if I type some stuff in the input fields before hitting it. It should always work.
3. If you do end up hiding the login | enroll buttons on the signup page, then you should have a button that takes the user back to the home page with the login dropdown open.
4. You should also add the css transitions to the dropdown similar to how their site is

See images below for more notes.

![image](https://user-images.githubusercontent.com/49164119/72094438-4aa07100-32cb-11ea-9763-b680b1729a56.png)

_________________________________________________________________________________________________________________

![image](https://user-images.githubusercontent.com/49164119/72094444-4ecc8e80-32cb-11ea-8535-0b9934bc0ace.png)

_________________________________________________________________________________________________________________


![image](https://user-images.githubusercontent.com/49164119/72094449-53914280-32cb-11ea-8831-822df88754fe.png)

_________________________________________________________________________________________________________________


![image](https://user-images.githubusercontent.com/49164119/72094459-57bd6000-32cb-11ea-9a72-752d9e6a5611.png)

_________________________________________________________________________________________________________________


![image](https://user-images.githubusercontent.com/49164119/72094475-5c821400-32cb-11ea-9aca-cfdd290159bc.png)

_________________________________________________________________________________________________________________


![image](https://user-images.githubusercontent.com/49164119/72094486-63108b80-32cb-11ea-997b-0814ab62bb85.png)

_________________________________________________________________________________________________________________


![image](https://user-images.githubusercontent.com/49164119/72094499-69066c80-32cb-11ea-8f54-0bd070954aa7.png)

_________________________________________________________________________________________________________________


![image](https://user-images.githubusercontent.com/49164119/72094772-fea1fc00-32cb-11ea-8961-6f6d65b73e0f.png)

**Comment by mkochalko** [comment]
- [ ] Backend: DB, model, controller, views
- [ ] Redux Loop: ajax, actions, reducer
- [ ] Presentational Components and Containers
- [ ] Styling
- [ ] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds


I was able to complete the items above except for opening the login dropdown if I have navigated from the signup page back to home.

**Comment by samwalker191** [comment]
No need to open up the login page when going from sign up to home. I think just not having the login button on the sign up page is fine.

One weird thing that will come into play in your next MVP is when you logout while on the user show page. It redirects you to the sign up page, I think you should redirect to the home page. 

Otherwise, everything looks much better! Nice job. I am closing this issue.
